name: CRON-CI
on:
  pull_request:
    branches: [master]
  schedule: [cron: "0 */4 * * *"]
  workflow_dispatch: 
env:

jobs:
  kind-csi-e2e:
    name: KIND-K8S-CSI-E2E
    # How to run K8S CSI e2e test
    # https://www.stackovercloud.com/2020/01/08/blog-testing-of-csi-drivers/
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        run: |
          # Don't run this in your local machine
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -f /home/runner/runners/2.305.0.tgz
          sudo rm -f /home/runner/runners/2.306.0.tgz
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/lib/google-cloud-sdk/
          sudo rm -rf /usr/lib/firefox
          sudo rm -rf /usr/share/swift
          sudo rm -rf /opt/microsoft/msedge
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/$KIND_VERSION/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin
      - name: Create Kind Cluster
        run: |
          bash scripts/create_kind_cluster.sh
      - name: Setup SSH
        run: |
          bash scripts/setup_ssh_for_cluster_nodes.sh
      - name: Datenlord Monitoring and Alerting Test
        run: |
          sh scripts/datenlord_monitor_test.sh
      - name: Deploy DatenLord to K8S
        run: |
          bash scripts/deploy_datenlord_to_k8s.sh false
      - name: Datenlord metric and logging test
        run: |
          bash scripts/datenlord_metrics_logging_test.sh
      - name: CSI E2E Test
        run: |
          bash scripts/csi_e2e_test.sh
      - name: Quick Start Test
        run: |
          bash scripts/quick_start_test.sh
      - name: DatenLord Perf Test
        run: |
          # TODO: avoid to re-create cluster
          kind delete cluster
          kind create cluster --config ./kind-config.yaml
          kind load docker-image ${DATENLORD_IMAGE}
          bash scripts/datenlord_perf_test.sh
      - name: Archive Perf Result
        uses: actions/upload-artifact@v2
        with:
          name: perf-report
          path: /tmp/output/*

      - name: Print DatenLord logs
        if: ${{ failure() }}
        run: |
          bash scripts/print_datenlord_logs.sh
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
